before_script:
  - export GOPATH=$(pwd)
  - export GOBIN=$GOPATH/bin

stages:
  - build
  - test

build-my-project:
  image: golang:1.6.2
  stage: build
  script:
    - mkdir $GOPATH/bin
    - go get
    - go build

test-my-project:
  image: golang:1.6.2
  stage: test
  script:
    - mkdir $GOPATH/bin
    - go get
    - go build
    - go test
