before_script:
  - export GOPATH=$(pwd)

stages:
  - build
  - test

build-my-project:
  image: go:1.6.2
  stage: build
  script:
    - go get
    - go build

test-my-project:
  image: go:1.6.2
  stage: test
  script:
    - go test
